In [11]:
import pandas as pd
import numpy as np

In [65]:
path = "data/sources/CHE/Transport/passenger/road_newstock_90_21.csv"
new = pd.read_csv(path, index_col=[0,1,2,3], header=0)
new = new.loc["Switzerland"]
path = "data/sources/CHE/Transport/passenger/road_totalstock_90_21.csv"
total = pd.read_csv(path, index_col=[0,1,2,3], header=0)
total = total.loc["Switzerland"]

In [67]:
group = "> Motorcycles"

lmv = new.xs(group)
fuel_types = lmv.index.unique(level="Fuel")
new_by_t_y = pd.DataFrame()
for i in fuel_types:
    fuel = lmv.xs(i, level="Fuel")
    new_by_t_y[i] = fuel.sum()

lmv = total.xs(group)
fuel_types = lmv.index.unique(level="Fuel")
tot_by_t_y = pd.DataFrame()
for i in fuel_types:
    fuel = lmv.xs(i, level="Fuel")
    tot_by_t_y[i] = fuel.sum()

In [68]:
total.index.unique(level="Vehicle group / type")

Index(['> Passenger cars', '... Passenger car', '> Passenger vehicles',
       '... Light motor vehicle', '... Heavy motor vehicle', '... Coach, bus',
       '... Minibus', '... Articulated bus', '> Motorcycles', '... Motorcicle',
       '... Small motorcicle', '... Three-wheel motorcicle',
       '... Motorcicle sidecar', '... Small three-wheel motorcicle',
       '... Lightweight ATV', '... Small ATV', '... Three-wheel ATV',
       '... Snowmobile'],
      dtype='object', name='Vehicle group / type')

In [69]:
tot_by_t_y

      Petrol  Diesel  Electricity  Other  Without motor
1990  298968       5          258     29              0
1991  318967       7          770     24              0
1992  335514       2          897     30              0
1993  347157      15          945     34              0
1994  356232      26          956     31              0
1995  369675      30          949     39              0
1996  380911      54          973     39              0
1997  409473      93         1052    122              0
1998  433432     230         1229    142              0
1999  462441     369         1392    146              0
2000  491666     510         1451    145              0
2001  519052     651         1547    131              0
2002  542690     756         1646     30              0
2003  564691     931         1690     36              0
2004  580108    1076         1765     49              0
2005  586748    1139         1733    613              0
2006  605182    1274         1729    467              0
2007  615175    1613         1742    612              0
2008  632070    1152         2047   1256              0
2009  638965    1112         2585    114              0
2010  646480    1084         3493    144              0
2011  659297    1064         5366    142              0
2012  670718    1021         7930    153              0
2013  677581     728         9523    157              0
2014  687523     864        10675    156              0
2015  697611     837        11424    149              0
2016  707702     797        11732    149              0
2017  716193     782        12026    147              0
2018  725731     760        12712    141              0
2019  729843     755        13807    137              0
2020  755597     791        15065    133              0
2021  770926     788        16955    131              0

In [58]:
new_by_t_y

,Petrol,Diesel,Petrol-electricity: conventional hybrid,Petrol-electricity: plug-in hybrid,Diesel-electricity: conventional hybrid,Diesel-electricity: plug-in hybrid,Electricity,Hydrogen,Gas (monovalent and bivalent),Other,Without motor
2006,0,3,0,0,0,0,0,0,0,0,0
2007,0,9,0,0,0,0,0,0,0,0,0
2008,0,14,0,0,0,0,0,0,0,0,0
2009,0,6,0,0,0,0,0,0,0,0,0
2010,0,7,0,0,0,0,0,0,0,0,0
2011,0,6,0,0,0,0,0,0,0,0,0
2012,0,5,0,0,0,0,0,0,0,0,0
2013,0,5,0,0,0,0,0,0,0,0,0
2014,0,6,0,0,0,0,0,0,0,0,0
2015,0,4,0,0,0,0,0,0,0,0,0
2016,0,1,0,0,0,0,0,0,0,0,0
2017,0,1,0,0,0,0,0,0,0,0,0
2018,0,11,0,0,0,0,0,0,0,0,0
2019,0,6,0,0,0,0,0,0,0,0,0
2020,0,8,0,0,0,0,0,0,0,0,0
2021,0,4,0,0,0,0,0,0,0,0,0